before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: cmd/cfft/main.go
    binary: cfft
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
