name: Go
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go:
          - '1.21'
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install esbuild
        run: npm -g install esbuild

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build & Test
        run: |
          go test -race ./...
        env:
          GO111MODULE: on
